schema_version = "1.0.0"

id = "fbx_mappers_toolkit"
name = "FBX Mapper's Toolkit"
version = "2.9.37"
tagline = "UV unwrap, material management and import/export for UE5 mapping"
maintainer = "Ja5mine"
type = "add-on"

blender_version_min = "5.1.0"

license = ["SPDX:GPL-3.0-or-later"]
category = "Import-Export"
